# This is a basic workflow to help you get started with Actions

name: Deploy Main on Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Notify start on Slack
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.5.0
        with:
          channel_id: channel_id
          status: STARTING
          color: warning
          
      - name: Run deploy command on Staging
        uses: appleboy/ssh-action@master
        with:
          host: host
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: port_number
          script_stop: true
          script: |
            cd rewrite-poc
            git pull
            docker compose -f docker-compose.production.yml down --remove-orphans
            docker compose -f docker-compose.production.yml build
            docker compose -f docker-compose.production.yml up -d
            
      - name: Notify success on Slack
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.5.0
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: channel_id
          status: SUCCESS
          color: good

      - name: Notify failure on Slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.5.0
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: channel_id
          status: FAILED
          color: danger
